Lesson 14
secretpray/Test-guru pull request #14
Opened 2020-10-18 12:12 UTC by secretpray

Используйте официальный клиент GitHub Octokit
Выводите ссылку на созданный gist во flash сообщении
Добавьте интернационализацию в сервис GistQuestionService
Добавьте модель Gist. У администратора сделайте вывод таблицы всех созданных gist. Таблица должна содержать обязательные колонки:
     Вопрос. Отображаются первые 25 символов тела вопроса в виде ссылки. По клике на ссылку отображается страница вопроса (действие show)
     Gist URL. Отображается хэш созданного gist в виде ссылки
     Пользователь. Отображается email пользователя который создал gist

 5. Поместите токен в .env файл и используйте github.com для его загрузки в окружение приложени

2020-10-18 19:49 UTC, BubuntuClu requested changes

2020-10-18 19:49 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +OCTOKIT = Octokit::Client.new(:access_token => ENV['ACCESS_TOKEN'])
хм, не уверен на счет этой строки, но не могу описать свое чувство, чем оно вызвано

2020-10-18 19:49 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      if result.html_url.present?
у октокита есть метод last_response, на основе него сделай хэлпер метод success? в своем сервисе и тут его используй, вместо проверки наличия атрибута

2020-10-18 19:49 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +        current_user.gists.create!(question: @test_passage.current_question, gist_url: result.html_url)
зачем бэнг метод? где rescue блок?

2020-10-18 20:01 UTC, secretpray commented on app/controllers/test_passages_controller.rb
> +OCTOKIT = Octokit::Client.new(:access_token => ENV['ACCESS_TOKEN'])
Мне тоже не нравится полное создание метода в константе, но еще меньше нравится создание клиента при передаче его непосредственно в качестве атрибута. Пытался сделать отдельным клиентом по примеру GitHubClient, но не получилось. Подскажи как красиво передать аргумент... 
Прим. Я думал вообще это в ENV перенести....

2020-10-19 12:16 UTC, BubuntuClu approved these changes

2020-10-19 12:16 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    @client = client.new(access_token: ACCESS_TOKEN) || GitHubClient.new
если тебе не передадут клиент никакой, у тебя будет `nil.new` и ошибка вылетит. дефолтное значение стоит в инициализаторе задать

2020-10-19 12:42 UTC, merged