Lesson 6
secretpray/Test-guru pull request #5
Opened 2020-09-22 17:25 UTC by secretpray

1. Определите scope-методы:
для выбора правильных Ответов
Для выбора Тестов по уровню сложности:
  простой (нулевой или первый уровень), 
       средний (со второго по четвёртый),
       сложный (с пятого и выше). Значение положительной бесконечности можно получить с помощью константы Float::INFINITY
scope-метод по умолчанию для получения Категорий, отсортированных по названию в порядке возрастания

2. Используйте scope-методы вместо методов моделей, которые были определены в предыдущих заданиях

3. Определите валидации данных:
Наличие атрибутов title, body, email в соответствующих моделях
Уровень Теста может быть только положительным целым числом
Может существовать только один Тест с данным названием и уровнем
У одного Вопроса может быть от 1-го до 4-х ответов.

2020-09-22 19:04 UTC, BubuntuClu requested changes

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/answer.rb
> +  validates :question_id, presence: true,
`belongs_to` за тебя делает подобную валидацию, так что тебе это не надо делать

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/category.rb
> +  validates_uniqueness_of :title, on: [ :create, :update ]
это старый тип валидации. уникальность можно указать как доп опцию в строке выше

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :by_category, -> (category) { joins(:category).where(categories: {title: category.to_s}).order(title: :desc) } # Test.by_category(:backend).pluck(:title)
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :category_id, presence: true,
аналогично ответу

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/test.rb
> +  validates_uniqueness_of :title, scope: :level # validates :title, uniqueness: { scope: :level }
то что в комментах выглядит лучше. и можно объединить с 8ой строкой

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/user.rb
> -  def by_level(level)
куда метод ушел? ты его можешь переписать имея в наличии ассоциацию

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_email_format_of :email, :message => 'Email format looks invalid. Did you mistype?' # ,:allow_nil => true
это тоже старый типа валидации. такое уже не принято юзать. надо поискать опцию для validates на предмет валидирования формата почты

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/user.rb
> +  # validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
а, ну вот он. это стоит использовать

2020-09-22 19:04 UTC, BubuntuClu commented on app/models/question.rb
> +  validates_uniqueness_of :body, on: [ :create, :update ]
тоже старый типа валидации

2020-09-22 19:34 UTC, secretpray commented on app/models/answer.rb
> +  validates :question_id, presence: true,
Fixed

2020-09-22 19:35 UTC, secretpray commented on app/models/category.rb
> +  validates_uniqueness_of :title, on: [ :create, :update ]
Fixed

2020-09-22 19:35 UTC, secretpray commented on app/models/test.rb
> +  scope :by_category, -> (category) { joins(:category).where(categories: {title: category.to_s}).order(title: :desc) } # Test.by_category(:backend).pluck(:title)
Fixed

2020-09-22 19:35 UTC, secretpray commented on app/models/test.rb
> +  validates_uniqueness_of :title, scope: :level # validates :title, uniqueness: { scope: :level }
Fixed

2020-09-22 19:35 UTC, secretpray commented on app/models/user.rb
> -  def by_level(level)
Fixed

2020-09-22 19:35 UTC, secretpray commented on app/models/user.rb
> +  validates_email_format_of :email, :message => 'Email format looks invalid. Did you mistype?' # ,:allow_nil => true
Fixed

2020-09-22 19:35 UTC, secretpray commented on app/models/user.rb
> +  # validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
Fixed

2020-09-22 19:35 UTC, secretpray commented on app/models/question.rb
> +  validates_uniqueness_of :body, on: [ :create, :update ]
Fixed

2020-09-22 19:35 UTC, secretpray commented
Fixed

2020-09-23 06:28 UTC, BubuntuClu approved these changes

2020-09-23 06:28 UTC, BubuntuClu commented on app/models/question.rb
> +  validates :body, presence: true, uniqueness: true
на самом деле уникальность в вопросе сомнительная штука. могут быть разные тесты, но с одинаковым вопросом

2020-09-23 06:28 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :by_category, -> (category) { joins(:category).where(categories: {title: category.to_s}) } # Test.by_category(:backend).order(title: :desc).pluck(:title)
метод не вернул. сейчас у тебя нет сортировки и выборки

2020-09-23 06:28 UTC, BubuntuClu commented on app/models/user.rb
> +    tests.where("level = :level", level: level).distinct # tests.where(level: level)
`tests.where(level: level)`

2020-09-23 06:28 UTC, BubuntuClu commented on app/models/category.rb
> +  validates :title, presence: true, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2020-09-23 16:02 UTC, merged